### PR TITLE
Milestone 1 : HTML Forms

### PR DESCRIPTION
**Pull request by OdongAlican**
## Mint.com SignUp Page clone: HTML Forms
In this milestone we:
- Created mint.com's Sign Up Page using HTML Forms

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review  in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @OdongAlican  and @alishabab , 👋

## You did an *amazing*🌟 ✨ job working on this project! 👊🏻  💯
I really liked the looks of your page.

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Work on your Pull Request message. Follow this [guideline](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) that tells you how to do it. :1st_place_medal: 

- **Remember setting up your linters!!**  Always look for the green checkmark on your commits so that you won't forget in the future.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by alishabab** [comment]
Hi @majovanilla , Thanks for the review. We have made the required changes.

**Comment by SofiBretz** [comment]
### Well done Team 👏

**Project Approved!**
You can merge 👍

SofiBretz.

**Comment by OdongAlican** [comment]
Hi @SofiBretz. Thanks a lot for your response. We will go ahead and merge it.

**Pull request merged**
